CREATE TABLE PRODUTO(
IDPRODUTO UNIQUEIDENTIFIER NOT NULL,
NOME NVARCHAR(150) NOT NULL,
PRECO DECIMAL (11, 2) NOT NULL,
QUANTIDADE INTEGER NOT NULL,
DATACADASTRO DATE NOT NULL,
PRIMARY KEY(IDPRODUTO))
GO